# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('idea', '0003_idea_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
