# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
